# Autogenerated using ProtoBuf.jl v1.2.2
# original file: rdf.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export RdfDatatypeEntry, RdfNameEntry, RdfIri, PhysicalStreamType, RdfLiteral
export RdfDefaultGraph, RdfPrefixEntry, RdfGraphEnd, LogicalStreamType
export RdfNamespaceDeclaration, RdfTriple, RdfGraphStart, RdfStreamOptions, RdfQuad
export RdfStreamRow, RdfStreamFrame
abstract type var"##Abstract#RdfLiteral" end
abstract type var"##Abstract#RdfTriple" end
abstract type var"##Abstract#RdfGraphStart" end
abstract type var"##Abstract#RdfQuad" end
abstract type var"##Abstract#RdfStreamRow" end


struct RdfDatatypeEntry
    id::UInt32
    value::String
end
PB.default_values(::Type{RdfDatatypeEntry}) = (;id = zero(UInt32), value = "")
PB.field_numbers(::Type{RdfDatatypeEntry}) = (;id = 1, value = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfDatatypeEntry})
    id = zero(UInt32)
    value = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            id = PB.decode(d, UInt32)
        elseif field_number == 2
            value = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfDatatypeEntry(id, value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfDatatypeEntry)
    initpos = position(e.io)
    x.id != zero(UInt32) && PB.encode(e, 1, x.id)
    !isempty(x.value) && PB.encode(e, 2, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfDatatypeEntry)
    encoded_size = 0
    x.id != zero(UInt32) && (encoded_size += PB._encoded_size(x.id, 1))
    !isempty(x.value) && (encoded_size += PB._encoded_size(x.value, 2))
    return encoded_size
end

struct RdfNameEntry
    id::UInt32
    value::String
end
PB.default_values(::Type{RdfNameEntry}) = (;id = zero(UInt32), value = "")
PB.field_numbers(::Type{RdfNameEntry}) = (;id = 1, value = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfNameEntry})
    id = zero(UInt32)
    value = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            id = PB.decode(d, UInt32)
        elseif field_number == 2
            value = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfNameEntry(id, value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfNameEntry)
    initpos = position(e.io)
    x.id != zero(UInt32) && PB.encode(e, 1, x.id)
    !isempty(x.value) && PB.encode(e, 2, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfNameEntry)
    encoded_size = 0
    x.id != zero(UInt32) && (encoded_size += PB._encoded_size(x.id, 1))
    !isempty(x.value) && (encoded_size += PB._encoded_size(x.value, 2))
    return encoded_size
end

struct RdfIri
    prefix_id::UInt32
    name_id::UInt32
end
PB.default_values(::Type{RdfIri}) = (;prefix_id = zero(UInt32), name_id = zero(UInt32))
PB.field_numbers(::Type{RdfIri}) = (;prefix_id = 1, name_id = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfIri})
    prefix_id = zero(UInt32)
    name_id = zero(UInt32)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            prefix_id = PB.decode(d, UInt32)
        elseif field_number == 2
            name_id = PB.decode(d, UInt32)
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfIri(prefix_id, name_id)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfIri)
    initpos = position(e.io)
    x.prefix_id != zero(UInt32) && PB.encode(e, 1, x.prefix_id)
    x.name_id != zero(UInt32) && PB.encode(e, 2, x.name_id)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfIri)
    encoded_size = 0
    x.prefix_id != zero(UInt32) && (encoded_size += PB._encoded_size(x.prefix_id, 1))
    x.name_id != zero(UInt32) && (encoded_size += PB._encoded_size(x.name_id, 2))
    return encoded_size
end

@enumx PhysicalStreamType PHYSICAL_STREAM_TYPE_UNSPECIFIED=0 PHYSICAL_STREAM_TYPE_TRIPLES=1 PHYSICAL_STREAM_TYPE_QUADS=2 PHYSICAL_STREAM_TYPE_GRAPHS=3

struct RdfLiteral{T1<:Union{Nothing,OneOf{<:Union{String,UInt32}}}}
    lex::String
    literalKind::T1
end
PB.oneof_field_types(::Type{RdfLiteral}) = (;
    literalKind = (;langtag=String, datatype=UInt32),
)
PB.default_values(::Type{RdfLiteral}) = (;lex = "", langtag = "", datatype = zero(UInt32))
PB.field_numbers(::Type{RdfLiteral}) = (;lex = 1, langtag = 2, datatype = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfLiteral})
    lex = ""
    literalKind = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            lex = PB.decode(d, String)
        elseif field_number == 2
            literalKind = OneOf(:langtag, PB.decode(d, String))
        elseif field_number == 3
            literalKind = OneOf(:datatype, PB.decode(d, UInt32))
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfLiteral{typeof(literalKind)}(lex, literalKind)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfLiteral)
    initpos = position(e.io)
    !isempty(x.lex) && PB.encode(e, 1, x.lex)
    if isnothing(x.literalKind);
    elseif x.literalKind.name === :langtag
        PB.encode(e, 2, x.literalKind[]::String)
    elseif x.literalKind.name === :datatype
        PB.encode(e, 3, x.literalKind[]::UInt32)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfLiteral)
    encoded_size = 0
    !isempty(x.lex) && (encoded_size += PB._encoded_size(x.lex, 1))
    if isnothing(x.literalKind);
    elseif x.literalKind.name === :langtag
        encoded_size += PB._encoded_size(x.literalKind[]::String, 2)
    elseif x.literalKind.name === :datatype
        encoded_size += PB._encoded_size(x.literalKind[]::UInt32, 3)
    end
    return encoded_size
end

struct RdfDefaultGraph end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfDefaultGraph})
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return RdfDefaultGraph()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfDefaultGraph)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfDefaultGraph)
    encoded_size = 0
    return encoded_size
end

struct RdfPrefixEntry
    id::UInt32
    value::String
end
PB.default_values(::Type{RdfPrefixEntry}) = (;id = zero(UInt32), value = "")
PB.field_numbers(::Type{RdfPrefixEntry}) = (;id = 1, value = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfPrefixEntry})
    id = zero(UInt32)
    value = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            id = PB.decode(d, UInt32)
        elseif field_number == 2
            value = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfPrefixEntry(id, value)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfPrefixEntry)
    initpos = position(e.io)
    x.id != zero(UInt32) && PB.encode(e, 1, x.id)
    !isempty(x.value) && PB.encode(e, 2, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfPrefixEntry)
    encoded_size = 0
    x.id != zero(UInt32) && (encoded_size += PB._encoded_size(x.id, 1))
    !isempty(x.value) && (encoded_size += PB._encoded_size(x.value, 2))
    return encoded_size
end

struct RdfGraphEnd end

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfGraphEnd})
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        Base.skip(d, wire_type)
    end
    return RdfGraphEnd()
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfGraphEnd)
    initpos = position(e.io)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfGraphEnd)
    encoded_size = 0
    return encoded_size
end

@enumx LogicalStreamType LOGICAL_STREAM_TYPE_UNSPECIFIED=0 LOGICAL_STREAM_TYPE_FLAT_TRIPLES=1 LOGICAL_STREAM_TYPE_FLAT_QUADS=2 LOGICAL_STREAM_TYPE_GRAPHS=3 LOGICAL_STREAM_TYPE_DATASETS=4 LOGICAL_STREAM_TYPE_SUBJECT_GRAPHS=13 LOGICAL_STREAM_TYPE_NAMED_GRAPHS=14 LOGICAL_STREAM_TYPE_TIMESTAMPED_NAMED_GRAPHS=114

struct RdfNamespaceDeclaration
    name::String
    value::Union{Nothing,RdfIri}
end
PB.default_values(::Type{RdfNamespaceDeclaration}) = (;name = "", value = nothing)
PB.field_numbers(::Type{RdfNamespaceDeclaration}) = (;name = 1, value = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfNamespaceDeclaration})
    name = ""
    value = Ref{Union{Nothing,RdfIri}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, value)
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfNamespaceDeclaration(name, value[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfNamespaceDeclaration)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    !isnothing(x.value) && PB.encode(e, 2, x.value)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfNamespaceDeclaration)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    !isnothing(x.value) && (encoded_size += PB._encoded_size(x.value, 2))
    return encoded_size
end

struct RdfTriple{T1<:Union{Nothing,OneOf{<:Union{RdfIri,String,RdfLiteral,var"##Abstract#RdfTriple"}}},T2<:Union{Nothing,OneOf{<:Union{RdfIri,String,RdfLiteral,var"##Abstract#RdfTriple"}}},T3<:Union{Nothing,OneOf{<:Union{RdfIri,String,RdfLiteral,var"##Abstract#RdfTriple"}}}} <: var"##Abstract#RdfTriple"
    subject::T1
    predicate::T2
    object::T3
end
PB.oneof_field_types(::Type{RdfTriple}) = (;
    subject = (;s_iri=RdfIri, s_bnode=String, s_literal=RdfLiteral, s_triple_term=RdfTriple),
    predicate = (;p_iri=RdfIri, p_bnode=String, p_literal=RdfLiteral, p_triple_term=RdfTriple),
    object = (;o_iri=RdfIri, o_bnode=String, o_literal=RdfLiteral, o_triple_term=RdfTriple),
)
PB.default_values(::Type{RdfTriple}) = (;s_iri = nothing, s_bnode = "", s_literal = nothing, s_triple_term = nothing, p_iri = nothing, p_bnode = "", p_literal = nothing, p_triple_term = nothing, o_iri = nothing, o_bnode = "", o_literal = nothing, o_triple_term = nothing)
PB.field_numbers(::Type{RdfTriple}) = (;s_iri = 1, s_bnode = 2, s_literal = 3, s_triple_term = 4, p_iri = 5, p_bnode = 6, p_literal = 7, p_triple_term = 8, o_iri = 9, o_bnode = 10, o_literal = 11, o_triple_term = 12)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfTriple})
    subject = nothing
    predicate = nothing
    object = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            subject = OneOf(:s_iri, PB.decode(d, Ref{RdfIri}))
        elseif field_number == 2
            subject = OneOf(:s_bnode, PB.decode(d, String))
        elseif field_number == 3
            subject = OneOf(:s_literal, PB.decode(d, Ref{RdfLiteral}))
        elseif field_number == 4
            subject = OneOf(:s_triple_term, PB.decode(d, Ref{RdfTriple}))
        elseif field_number == 5
            predicate = OneOf(:p_iri, PB.decode(d, Ref{RdfIri}))
        elseif field_number == 6
            predicate = OneOf(:p_bnode, PB.decode(d, String))
        elseif field_number == 7
            predicate = OneOf(:p_literal, PB.decode(d, Ref{RdfLiteral}))
        elseif field_number == 8
            predicate = OneOf(:p_triple_term, PB.decode(d, Ref{RdfTriple}))
        elseif field_number == 9
            object = OneOf(:o_iri, PB.decode(d, Ref{RdfIri}))
        elseif field_number == 10
            object = OneOf(:o_bnode, PB.decode(d, String))
        elseif field_number == 11
            object = OneOf(:o_literal, PB.decode(d, Ref{RdfLiteral}))
        elseif field_number == 12
            object = OneOf(:o_triple_term, PB.decode(d, Ref{RdfTriple}))
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfTriple{typeof(subject),typeof(predicate),typeof(object)}(subject, predicate, object)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfTriple)
    initpos = position(e.io)
    if isnothing(x.subject);
    elseif x.subject.name === :s_iri
        PB.encode(e, 1, x.subject[]::RdfIri)
    elseif x.subject.name === :s_bnode
        PB.encode(e, 2, x.subject[]::String)
    elseif x.subject.name === :s_literal
        PB.encode(e, 3, x.subject[]::RdfLiteral)
    elseif x.subject.name === :s_triple_term
        PB.encode(e, 4, x.subject[]::RdfTriple)
    end
    if isnothing(x.predicate);
    elseif x.predicate.name === :p_iri
        PB.encode(e, 5, x.predicate[]::RdfIri)
    elseif x.predicate.name === :p_bnode
        PB.encode(e, 6, x.predicate[]::String)
    elseif x.predicate.name === :p_literal
        PB.encode(e, 7, x.predicate[]::RdfLiteral)
    elseif x.predicate.name === :p_triple_term
        PB.encode(e, 8, x.predicate[]::RdfTriple)
    end
    if isnothing(x.object);
    elseif x.object.name === :o_iri
        PB.encode(e, 9, x.object[]::RdfIri)
    elseif x.object.name === :o_bnode
        PB.encode(e, 10, x.object[]::String)
    elseif x.object.name === :o_literal
        PB.encode(e, 11, x.object[]::RdfLiteral)
    elseif x.object.name === :o_triple_term
        PB.encode(e, 12, x.object[]::RdfTriple)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfTriple)
    encoded_size = 0
    if isnothing(x.subject);
    elseif x.subject.name === :s_iri
        encoded_size += PB._encoded_size(x.subject[]::RdfIri, 1)
    elseif x.subject.name === :s_bnode
        encoded_size += PB._encoded_size(x.subject[]::String, 2)
    elseif x.subject.name === :s_literal
        encoded_size += PB._encoded_size(x.subject[]::RdfLiteral, 3)
    elseif x.subject.name === :s_triple_term
        encoded_size += PB._encoded_size(x.subject[]::RdfTriple, 4)
    end
    if isnothing(x.predicate);
    elseif x.predicate.name === :p_iri
        encoded_size += PB._encoded_size(x.predicate[]::RdfIri, 5)
    elseif x.predicate.name === :p_bnode
        encoded_size += PB._encoded_size(x.predicate[]::String, 6)
    elseif x.predicate.name === :p_literal
        encoded_size += PB._encoded_size(x.predicate[]::RdfLiteral, 7)
    elseif x.predicate.name === :p_triple_term
        encoded_size += PB._encoded_size(x.predicate[]::RdfTriple, 8)
    end
    if isnothing(x.object);
    elseif x.object.name === :o_iri
        encoded_size += PB._encoded_size(x.object[]::RdfIri, 9)
    elseif x.object.name === :o_bnode
        encoded_size += PB._encoded_size(x.object[]::String, 10)
    elseif x.object.name === :o_literal
        encoded_size += PB._encoded_size(x.object[]::RdfLiteral, 11)
    elseif x.object.name === :o_triple_term
        encoded_size += PB._encoded_size(x.object[]::RdfTriple, 12)
    end
    return encoded_size
end

struct RdfGraphStart{T1<:Union{Nothing,OneOf{<:Union{RdfIri,String,RdfDefaultGraph,RdfLiteral}}}}
    graph::T1
end
PB.oneof_field_types(::Type{RdfGraphStart}) = (;
    graph = (;g_iri=RdfIri, g_bnode=String, g_default_graph=RdfDefaultGraph, g_literal=RdfLiteral),
)
PB.default_values(::Type{RdfGraphStart}) = (;g_iri = nothing, g_bnode = "", g_default_graph = nothing, g_literal = nothing)
PB.field_numbers(::Type{RdfGraphStart}) = (;g_iri = 1, g_bnode = 2, g_default_graph = 3, g_literal = 4)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfGraphStart})
    graph = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            graph = OneOf(:g_iri, PB.decode(d, Ref{RdfIri}))
        elseif field_number == 2
            graph = OneOf(:g_bnode, PB.decode(d, String))
        elseif field_number == 3
            graph = OneOf(:g_default_graph, PB.decode(d, Ref{RdfDefaultGraph}))
        elseif field_number == 4
            graph = OneOf(:g_literal, PB.decode(d, Ref{RdfLiteral}))
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfGraphStart{typeof(graph)}(graph)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfGraphStart)
    initpos = position(e.io)
    if isnothing(x.graph);
    elseif x.graph.name === :g_iri
        PB.encode(e, 1, x.graph[]::RdfIri)
    elseif x.graph.name === :g_bnode
        PB.encode(e, 2, x.graph[]::String)
    elseif x.graph.name === :g_default_graph
        PB.encode(e, 3, x.graph[]::RdfDefaultGraph)
    elseif x.graph.name === :g_literal
        PB.encode(e, 4, x.graph[]::RdfLiteral)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfGraphStart)
    encoded_size = 0
    if isnothing(x.graph);
    elseif x.graph.name === :g_iri
        encoded_size += PB._encoded_size(x.graph[]::RdfIri, 1)
    elseif x.graph.name === :g_bnode
        encoded_size += PB._encoded_size(x.graph[]::String, 2)
    elseif x.graph.name === :g_default_graph
        encoded_size += PB._encoded_size(x.graph[]::RdfDefaultGraph, 3)
    elseif x.graph.name === :g_literal
        encoded_size += PB._encoded_size(x.graph[]::RdfLiteral, 4)
    end
    return encoded_size
end

struct RdfStreamOptions
    stream_name::String
    physical_type::PhysicalStreamType.T
    generalized_statements::Bool
    rdf_star::Bool
    max_name_table_size::UInt32
    max_prefix_table_size::UInt32
    max_datatype_table_size::UInt32
    logical_type::LogicalStreamType.T
    version::UInt32
end
PB.default_values(::Type{RdfStreamOptions}) = (;stream_name = "", physical_type = PhysicalStreamType.PHYSICAL_STREAM_TYPE_UNSPECIFIED, generalized_statements = false, rdf_star = false, max_name_table_size = zero(UInt32), max_prefix_table_size = zero(UInt32), max_datatype_table_size = zero(UInt32), logical_type = LogicalStreamType.LOGICAL_STREAM_TYPE_UNSPECIFIED, version = zero(UInt32))
PB.field_numbers(::Type{RdfStreamOptions}) = (;stream_name = 1, physical_type = 2, generalized_statements = 3, rdf_star = 4, max_name_table_size = 9, max_prefix_table_size = 10, max_datatype_table_size = 11, logical_type = 14, version = 15)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfStreamOptions})
    stream_name = ""
    physical_type = PhysicalStreamType.PHYSICAL_STREAM_TYPE_UNSPECIFIED
    generalized_statements = false
    rdf_star = false
    max_name_table_size = zero(UInt32)
    max_prefix_table_size = zero(UInt32)
    max_datatype_table_size = zero(UInt32)
    logical_type = LogicalStreamType.LOGICAL_STREAM_TYPE_UNSPECIFIED
    version = zero(UInt32)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            stream_name = PB.decode(d, String)
        elseif field_number == 2
            physical_type = PB.decode(d, PhysicalStreamType.T)
        elseif field_number == 3
            generalized_statements = PB.decode(d, Bool)
        elseif field_number == 4
            rdf_star = PB.decode(d, Bool)
        elseif field_number == 9
            max_name_table_size = PB.decode(d, UInt32)
        elseif field_number == 10
            max_prefix_table_size = PB.decode(d, UInt32)
        elseif field_number == 11
            max_datatype_table_size = PB.decode(d, UInt32)
        elseif field_number == 14
            logical_type = PB.decode(d, LogicalStreamType.T)
        elseif field_number == 15
            version = PB.decode(d, UInt32)
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfStreamOptions(stream_name, physical_type, generalized_statements, rdf_star, max_name_table_size, max_prefix_table_size, max_datatype_table_size, logical_type, version)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfStreamOptions)
    initpos = position(e.io)
    !isempty(x.stream_name) && PB.encode(e, 1, x.stream_name)
    x.physical_type != PhysicalStreamType.PHYSICAL_STREAM_TYPE_UNSPECIFIED && PB.encode(e, 2, x.physical_type)
    x.generalized_statements != false && PB.encode(e, 3, x.generalized_statements)
    x.rdf_star != false && PB.encode(e, 4, x.rdf_star)
    x.max_name_table_size != zero(UInt32) && PB.encode(e, 9, x.max_name_table_size)
    x.max_prefix_table_size != zero(UInt32) && PB.encode(e, 10, x.max_prefix_table_size)
    x.max_datatype_table_size != zero(UInt32) && PB.encode(e, 11, x.max_datatype_table_size)
    x.logical_type != LogicalStreamType.LOGICAL_STREAM_TYPE_UNSPECIFIED && PB.encode(e, 14, x.logical_type)
    x.version != zero(UInt32) && PB.encode(e, 15, x.version)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfStreamOptions)
    encoded_size = 0
    !isempty(x.stream_name) && (encoded_size += PB._encoded_size(x.stream_name, 1))
    x.physical_type != PhysicalStreamType.PHYSICAL_STREAM_TYPE_UNSPECIFIED && (encoded_size += PB._encoded_size(x.physical_type, 2))
    x.generalized_statements != false && (encoded_size += PB._encoded_size(x.generalized_statements, 3))
    x.rdf_star != false && (encoded_size += PB._encoded_size(x.rdf_star, 4))
    x.max_name_table_size != zero(UInt32) && (encoded_size += PB._encoded_size(x.max_name_table_size, 9))
    x.max_prefix_table_size != zero(UInt32) && (encoded_size += PB._encoded_size(x.max_prefix_table_size, 10))
    x.max_datatype_table_size != zero(UInt32) && (encoded_size += PB._encoded_size(x.max_datatype_table_size, 11))
    x.logical_type != LogicalStreamType.LOGICAL_STREAM_TYPE_UNSPECIFIED && (encoded_size += PB._encoded_size(x.logical_type, 14))
    x.version != zero(UInt32) && (encoded_size += PB._encoded_size(x.version, 15))
    return encoded_size
end

struct RdfQuad{T1<:Union{Nothing,OneOf{<:Union{RdfIri,String,RdfLiteral,RdfTriple}}},T2<:Union{Nothing,OneOf{<:Union{RdfIri,String,RdfLiteral,RdfTriple}}},T3<:Union{Nothing,OneOf{<:Union{RdfIri,String,RdfLiteral,RdfTriple}}},T4<:Union{Nothing,OneOf{<:Union{RdfIri,String,RdfDefaultGraph,RdfLiteral}}}}
    subject::T1
    predicate::T2
    object::T3
    graph::T4
end
PB.oneof_field_types(::Type{RdfQuad}) = (;
    subject = (;s_iri=RdfIri, s_bnode=String, s_literal=RdfLiteral, s_triple_term=RdfTriple),
    predicate = (;p_iri=RdfIri, p_bnode=String, p_literal=RdfLiteral, p_triple_term=RdfTriple),
    object = (;o_iri=RdfIri, o_bnode=String, o_literal=RdfLiteral, o_triple_term=RdfTriple),
    graph = (;g_iri=RdfIri, g_bnode=String, g_default_graph=RdfDefaultGraph, g_literal=RdfLiteral),
)
PB.default_values(::Type{RdfQuad}) = (;s_iri = nothing, s_bnode = "", s_literal = nothing, s_triple_term = nothing, p_iri = nothing, p_bnode = "", p_literal = nothing, p_triple_term = nothing, o_iri = nothing, o_bnode = "", o_literal = nothing, o_triple_term = nothing, g_iri = nothing, g_bnode = "", g_default_graph = nothing, g_literal = nothing)
PB.field_numbers(::Type{RdfQuad}) = (;s_iri = 1, s_bnode = 2, s_literal = 3, s_triple_term = 4, p_iri = 5, p_bnode = 6, p_literal = 7, p_triple_term = 8, o_iri = 9, o_bnode = 10, o_literal = 11, o_triple_term = 12, g_iri = 13, g_bnode = 14, g_default_graph = 15, g_literal = 16)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfQuad})
    subject = nothing
    predicate = nothing
    object = nothing
    graph = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            subject = OneOf(:s_iri, PB.decode(d, Ref{RdfIri}))
        elseif field_number == 2
            subject = OneOf(:s_bnode, PB.decode(d, String))
        elseif field_number == 3
            subject = OneOf(:s_literal, PB.decode(d, Ref{RdfLiteral}))
        elseif field_number == 4
            subject = OneOf(:s_triple_term, PB.decode(d, Ref{RdfTriple}))
        elseif field_number == 5
            predicate = OneOf(:p_iri, PB.decode(d, Ref{RdfIri}))
        elseif field_number == 6
            predicate = OneOf(:p_bnode, PB.decode(d, String))
        elseif field_number == 7
            predicate = OneOf(:p_literal, PB.decode(d, Ref{RdfLiteral}))
        elseif field_number == 8
            predicate = OneOf(:p_triple_term, PB.decode(d, Ref{RdfTriple}))
        elseif field_number == 9
            object = OneOf(:o_iri, PB.decode(d, Ref{RdfIri}))
        elseif field_number == 10
            object = OneOf(:o_bnode, PB.decode(d, String))
        elseif field_number == 11
            object = OneOf(:o_literal, PB.decode(d, Ref{RdfLiteral}))
        elseif field_number == 12
            object = OneOf(:o_triple_term, PB.decode(d, Ref{RdfTriple}))
        elseif field_number == 13
            graph = OneOf(:g_iri, PB.decode(d, Ref{RdfIri}))
        elseif field_number == 14
            graph = OneOf(:g_bnode, PB.decode(d, String))
        elseif field_number == 15
            graph = OneOf(:g_default_graph, PB.decode(d, Ref{RdfDefaultGraph}))
        elseif field_number == 16
            graph = OneOf(:g_literal, PB.decode(d, Ref{RdfLiteral}))
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfQuad{typeof(subject),typeof(predicate),typeof(object),typeof(graph)}(subject, predicate, object, graph)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfQuad)
    initpos = position(e.io)
    if isnothing(x.subject);
    elseif x.subject.name === :s_iri
        PB.encode(e, 1, x.subject[]::RdfIri)
    elseif x.subject.name === :s_bnode
        PB.encode(e, 2, x.subject[]::String)
    elseif x.subject.name === :s_literal
        PB.encode(e, 3, x.subject[]::RdfLiteral)
    elseif x.subject.name === :s_triple_term
        PB.encode(e, 4, x.subject[]::RdfTriple)
    end
    if isnothing(x.predicate);
    elseif x.predicate.name === :p_iri
        PB.encode(e, 5, x.predicate[]::RdfIri)
    elseif x.predicate.name === :p_bnode
        PB.encode(e, 6, x.predicate[]::String)
    elseif x.predicate.name === :p_literal
        PB.encode(e, 7, x.predicate[]::RdfLiteral)
    elseif x.predicate.name === :p_triple_term
        PB.encode(e, 8, x.predicate[]::RdfTriple)
    end
    if isnothing(x.object);
    elseif x.object.name === :o_iri
        PB.encode(e, 9, x.object[]::RdfIri)
    elseif x.object.name === :o_bnode
        PB.encode(e, 10, x.object[]::String)
    elseif x.object.name === :o_literal
        PB.encode(e, 11, x.object[]::RdfLiteral)
    elseif x.object.name === :o_triple_term
        PB.encode(e, 12, x.object[]::RdfTriple)
    end
    if isnothing(x.graph);
    elseif x.graph.name === :g_iri
        PB.encode(e, 13, x.graph[]::RdfIri)
    elseif x.graph.name === :g_bnode
        PB.encode(e, 14, x.graph[]::String)
    elseif x.graph.name === :g_default_graph
        PB.encode(e, 15, x.graph[]::RdfDefaultGraph)
    elseif x.graph.name === :g_literal
        PB.encode(e, 16, x.graph[]::RdfLiteral)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfQuad)
    encoded_size = 0
    if isnothing(x.subject);
    elseif x.subject.name === :s_iri
        encoded_size += PB._encoded_size(x.subject[]::RdfIri, 1)
    elseif x.subject.name === :s_bnode
        encoded_size += PB._encoded_size(x.subject[]::String, 2)
    elseif x.subject.name === :s_literal
        encoded_size += PB._encoded_size(x.subject[]::RdfLiteral, 3)
    elseif x.subject.name === :s_triple_term
        encoded_size += PB._encoded_size(x.subject[]::RdfTriple, 4)
    end
    if isnothing(x.predicate);
    elseif x.predicate.name === :p_iri
        encoded_size += PB._encoded_size(x.predicate[]::RdfIri, 5)
    elseif x.predicate.name === :p_bnode
        encoded_size += PB._encoded_size(x.predicate[]::String, 6)
    elseif x.predicate.name === :p_literal
        encoded_size += PB._encoded_size(x.predicate[]::RdfLiteral, 7)
    elseif x.predicate.name === :p_triple_term
        encoded_size += PB._encoded_size(x.predicate[]::RdfTriple, 8)
    end
    if isnothing(x.object);
    elseif x.object.name === :o_iri
        encoded_size += PB._encoded_size(x.object[]::RdfIri, 9)
    elseif x.object.name === :o_bnode
        encoded_size += PB._encoded_size(x.object[]::String, 10)
    elseif x.object.name === :o_literal
        encoded_size += PB._encoded_size(x.object[]::RdfLiteral, 11)
    elseif x.object.name === :o_triple_term
        encoded_size += PB._encoded_size(x.object[]::RdfTriple, 12)
    end
    if isnothing(x.graph);
    elseif x.graph.name === :g_iri
        encoded_size += PB._encoded_size(x.graph[]::RdfIri, 13)
    elseif x.graph.name === :g_bnode
        encoded_size += PB._encoded_size(x.graph[]::String, 14)
    elseif x.graph.name === :g_default_graph
        encoded_size += PB._encoded_size(x.graph[]::RdfDefaultGraph, 15)
    elseif x.graph.name === :g_literal
        encoded_size += PB._encoded_size(x.graph[]::RdfLiteral, 16)
    end
    return encoded_size
end

struct RdfStreamRow{T1<:Union{Nothing,OneOf{<:Union{RdfStreamOptions,RdfTriple,RdfQuad,RdfGraphStart,RdfGraphEnd,RdfNamespaceDeclaration,RdfNameEntry,RdfPrefixEntry,RdfDatatypeEntry}}}}
    row::T1
end
PB.oneof_field_types(::Type{RdfStreamRow}) = (;
    row = (;options=RdfStreamOptions, triple=RdfTriple, quad=RdfQuad, graph_start=RdfGraphStart, graph_end=RdfGraphEnd, namespace=RdfNamespaceDeclaration, name=RdfNameEntry, prefix=RdfPrefixEntry, datatype=RdfDatatypeEntry),
)
PB.default_values(::Type{RdfStreamRow}) = (;options = nothing, triple = nothing, quad = nothing, graph_start = nothing, graph_end = nothing, namespace = nothing, name = nothing, prefix = nothing, datatype = nothing)
PB.field_numbers(::Type{RdfStreamRow}) = (;options = 1, triple = 2, quad = 3, graph_start = 4, graph_end = 5, namespace = 6, name = 9, prefix = 10, datatype = 11)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfStreamRow})
    row = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            row = OneOf(:options, PB.decode(d, Ref{RdfStreamOptions}))
        elseif field_number == 2
            row = OneOf(:triple, PB.decode(d, Ref{RdfTriple}))
        elseif field_number == 3
            row = OneOf(:quad, PB.decode(d, Ref{RdfQuad}))
        elseif field_number == 4
            row = OneOf(:graph_start, PB.decode(d, Ref{RdfGraphStart}))
        elseif field_number == 5
            row = OneOf(:graph_end, PB.decode(d, Ref{RdfGraphEnd}))
        elseif field_number == 6
            row = OneOf(:namespace, PB.decode(d, Ref{RdfNamespaceDeclaration}))
        elseif field_number == 9
            row = OneOf(:name, PB.decode(d, Ref{RdfNameEntry}))
        elseif field_number == 10
            row = OneOf(:prefix, PB.decode(d, Ref{RdfPrefixEntry}))
        elseif field_number == 11
            row = OneOf(:datatype, PB.decode(d, Ref{RdfDatatypeEntry}))
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfStreamRow{typeof(row)}(row)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfStreamRow)
    initpos = position(e.io)
    if isnothing(x.row);
    elseif x.row.name === :options
        PB.encode(e, 1, x.row[]::RdfStreamOptions)
    elseif x.row.name === :triple
        PB.encode(e, 2, x.row[]::RdfTriple)
    elseif x.row.name === :quad
        PB.encode(e, 3, x.row[]::RdfQuad)
    elseif x.row.name === :graph_start
        PB.encode(e, 4, x.row[]::RdfGraphStart)
    elseif x.row.name === :graph_end
        PB.encode(e, 5, x.row[]::RdfGraphEnd)
    elseif x.row.name === :namespace
        PB.encode(e, 6, x.row[]::RdfNamespaceDeclaration)
    elseif x.row.name === :name
        PB.encode(e, 9, x.row[]::RdfNameEntry)
    elseif x.row.name === :prefix
        PB.encode(e, 10, x.row[]::RdfPrefixEntry)
    elseif x.row.name === :datatype
        PB.encode(e, 11, x.row[]::RdfDatatypeEntry)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfStreamRow)
    encoded_size = 0
    if isnothing(x.row);
    elseif x.row.name === :options
        encoded_size += PB._encoded_size(x.row[]::RdfStreamOptions, 1)
    elseif x.row.name === :triple
        encoded_size += PB._encoded_size(x.row[]::RdfTriple, 2)
    elseif x.row.name === :quad
        encoded_size += PB._encoded_size(x.row[]::RdfQuad, 3)
    elseif x.row.name === :graph_start
        encoded_size += PB._encoded_size(x.row[]::RdfGraphStart, 4)
    elseif x.row.name === :graph_end
        encoded_size += PB._encoded_size(x.row[]::RdfGraphEnd, 5)
    elseif x.row.name === :namespace
        encoded_size += PB._encoded_size(x.row[]::RdfNamespaceDeclaration, 6)
    elseif x.row.name === :name
        encoded_size += PB._encoded_size(x.row[]::RdfNameEntry, 9)
    elseif x.row.name === :prefix
        encoded_size += PB._encoded_size(x.row[]::RdfPrefixEntry, 10)
    elseif x.row.name === :datatype
        encoded_size += PB._encoded_size(x.row[]::RdfDatatypeEntry, 11)
    end
    return encoded_size
end

struct RdfStreamFrame
    rows::Vector{<:RdfStreamRow}
    metadata::Dict{String,Vector{UInt8}}
end
PB.default_values(::Type{RdfStreamFrame}) = (;rows = Vector{RdfStreamRow}(), metadata = Dict{String,Vector{UInt8}}())
PB.field_numbers(::Type{RdfStreamFrame}) = (;rows = 1, metadata = 15)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:RdfStreamFrame})
    rows = PB.BufferedVector{RdfStreamRow}()
    metadata = Dict{String,Vector{UInt8}}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, rows)
        elseif field_number == 15
            PB.decode!(d, metadata)
        else
            Base.skip(d, wire_type)
        end
    end
    return RdfStreamFrame(rows[], metadata)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::RdfStreamFrame)
    initpos = position(e.io)
    !isempty(x.rows) && PB.encode(e, 1, x.rows)
    !isempty(x.metadata) && PB.encode(e, 15, x.metadata)
    return position(e.io) - initpos
end
function PB._encoded_size(x::RdfStreamFrame)
    encoded_size = 0
    !isempty(x.rows) && (encoded_size += PB._encoded_size(x.rows, 1))
    !isempty(x.metadata) && (encoded_size += PB._encoded_size(x.metadata, 15))
    return encoded_size
end
